name: Deploy Pandoc

on:
  - push

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install goplantuml
        run: |
          go install github.com/jfeliu007/goplantuml/cmd/goplantuml@v1.5.2
      - run: mkdir out
      - name: Create UML PNGs
        run: |
          cd src
          for f in $(find -mindepth 2 -maxdepth 2 -type d); do
            fn=$(echo $f | sed "s/.\\///;y/\\//_/" )
            goplantuml -recursive $f > ../out/$fn.puml
          done
          goplantuml -recursive . > ../out/all.puml
      - name: Generate UML PNG
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tpng out/*.puml
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: plantuml
          path: |
            out/*.png
  pandoc:
     runs-on: ubuntu-latest
     needs:
      - plantuml
     container: 
       image: pandoc/ubuntu-latex:2.14.2
     steps:
      - name: Setup env
        run: |
          apt update && apt install -y git wget xz-utils
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Prepare Pandoc Crossref
        run: |
          wget -O pandoc/pandoc-crossref-Linux.tar.xz https://github.com/lierdakil/pandoc-crossref/releases/latest/download/pandoc-crossref-Linux.tar.xz
          tar --xz -C pandoc -xf pandoc/pandoc-crossref-Linux.tar.xz
      - name: Load UML images
        uses: actions/download-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: plantuml
          path: img/plantuml
      - name: Build PDF
        run: |
          mkdir -p out
          PATH=$PATH:/opt/texlive/texdir/bin/x86_64-linux
          chmod +x ./pandoc/workflow.sh
          ./pandoc/workflow.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: documentation
          path: |
            out/doc.pdf
            out/*.png
          if-no-files-found: error
